### ISSUE TITLE
Page Flow Design

### ISSUE THREAD

**Issue by doctormo** [Ashmont-Valley/ashmont-valley-website#16]
The current edit flow for meetings is messed up. This is because we have edit defined as a step in the meeting process rather than an outside step.

To re-factor this design we need to do a few things:

 1. Create a new Edit Meeting which will only be available to meetings that have not been started. The form will allow all fields in the Create Meeting to be edited (should use the same form)
 2. A Delete Meeting, for any meeting not yet started.
 3. The current Edit Meeting should be renamed to "Prepare Meeting"
 4. The workflow will go: Meetings List -> Prepare Meeting -> Start Meeting -> End Meeting

There are further refinements to the work flow, but this is complex enough for this task.

**Comment by jdynes** [comment]
What buttons are there supposed to be and which pages should they be in?

**Comment by doctormo** [comment]
Edit like create should just have a 'Save Edits' button and a Cancel button. 
The Delete confirmation page should have a Confirm Delete and Cancel button
The Prepare Meeting page should have a "Start Meeting" button and a "Cancel" button
The Proceedings page should have an "End Meeting"  button and nothing more, this should redirect to the meeting details.

The list index will contain the entry buttons for these items.
